spring:
  datasource:
    data-username: sa
    url: jdbc:h2:~/TEST;DB_CLOSE_ON_EXIT=FALSE;DATABASE_TO_UPPER=TRUE;INIT=CREATE SCHEMA IF NOT EXISTS PUBLIC

logging:
  level:
    org.springframework.batch: TRACE
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql: DEBUG
    liquibase: TRACE
